### ISSUE TITLE
R 4.4.1: The provided R version is likely wrong.

### ISSUE THREAD

**Issue by artur-sannikov** [b-rodrigues/rix#283]
I run `nix-shell --expr "$(curl -sl https://raw.githubusercontent.com/b-rodrigues/rix/master/inst/extdata/default.nix)"` and then in the Nix environment I wrote this code:

```R
library(rix)
rix(
  r_ver = "4.4.1",
  r_pkgs = NULL,
  system_pkgs = NULL,
  git_pkgs = NULL,
  ide = "code",
  project_path = ".",
  overwrite = TRUE
)
```
I get this error:

```
Error in get_latest(r_ver) : The provided R version is likely wrong.
Please check that you provided a correct R version.
You can list available versions using `available_r()`.
You can also directly provide a commit, but you need to make sure it points to the right repo used by `rix()`.
You can also use 'bleeding_edge' and 'frozen_edge'.
```

If I use R 4.4.0 (`r_ver = 4.4.0`), I get

```
Warning message:
In rix(r_ver = "4.4.0", r_pkgs = NULL, system_pkgs = NULL, git_pkgs = NULL,  :
  You chose '4.4.0' as the R version, however this version is not available in nixpkgs. The generated expression will thus install R version 4.4.1.
```

**Comment by b-rodrigues** [comment]
Hello, 

yes, this is expected. Because R version 4.4.1 is the latest version available, to use it, you need to pass "latest". Then, once a new R version will be available, then you can pass "4.4.1" because this will refer to specific commit. As for 4.4.0, it’s as the warning explains, that version is not available on nixpkgs, so we can’t provide it either.
